services:
  jirasoftware:
    image: atlassian/jira-software:latest
    container_name: jira-software
    restart: always
    volumes:
      - ./jirasoftwaredata:/var/atlassian/application-data/jira/shared
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      - "ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb"
      - "ATL_JDBC_USER=jira"
      - "ATL_JDBC_PASSWORD=jellyfish"
      - "ATL_DB_DRIVER=org.postgresql.Driver"
      - "ATL_DB_TYPE=postgres72"
      - "JVM_MINIMUM_MEMORY=2048m"
      - "JVM_MAXIMUM_MEMORY=4096m"
      - 'JVM_SUPPORT_RECOMMENDED_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"'
      - "CLUSTERED=true"
      - "JIRA_NODE_ID=node_1"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      - jiranet
  postgresql:
    image: postgres:9.5-alpine
    container_name: postgresql
    restart: always
    volumes:
      - ./postgresqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=jira"
      - "POSTGRES_PASSWORD=welcome123"
      - "POSTGRES_DB=jiradb"
      - "POSTGRES_ENCODING=UNICODE"
      - "POSTGRES_COLLATE=C"
      - "POSTGRES_COLLATE_TYPE=C"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      - jiranet
volumes:
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge
